name: Go

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install hwloc libhwloc-dev jq ocl-icd-opencl-dev
      - name: Build
        run: make clean all

      - name: Test
        run: go test -v ./...